name: Submit Branch
on:
  issues:
    types: [opened, reopened]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 13
      uses: actions/setup-node@v1
      with:
        node-version: '13'

    - name: npm install
      run: npm install

    - name: Commit Branch
      run: node submitPr.js
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_BODY: ${{ github.event.issue.body }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
