name: create-submit-pr
on:
  issues:
    types: [opened, reopened]

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 13
      uses: actions/setup-node@v1
      with:
        node-version: '13'

    - name: npm install
      run: npm install

    - name: Commit Branch
      run: node submitPr.js
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_BODY: ${{ github.event.issue.body }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: ${{ format('submit-{0}', github.event.issue.number) }}
