name: create-submit-pr

on:
  push:
    branches:
      - 'submit-*'

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
